### ISSUE TITLE
Link to Update Option Missing

### ISSUE THREAD

**Issue by trowgundam** [Matthew-Hsu/PiPass#12]
This is a cosmetic issue, no functionality is broken. The option in the menu to "Update" is missing on 2 pages. The "Dashboard" and PiPass "Stop" pages. All other pages have the link available.

**Comment by nagledb** [comment]
The link for Update appears for me on both of those pages. Maybe your browser is showing you a cached older version?

**Comment by trowgundam** [comment]
Ya, that seems to be the case. Odd, that none of the other pages I used more often didn't show up, maybe due to them being the setting pages so the forced update stuff he added prevented it. Still, my bad.

**Comment by Corruptinglyneedful** [comment]
This happened to me too, when I first booted the Dashboard, than it just later reappeared.  I even did a force reload.

Not sure what was up with that.
