### ISSUE TITLE
Dashboard EN-FR Localization

### ISSUE THREAD

**Issue by JohWiiner** [Matthew-Hsu/PiPass#16]
I, great job for PiPass thanks.

i make that for me today, it's a bilingual interface, if you want for a futur release.
http://www.wizupload.com/62jzj6i3hzj3

**Comment by Matthew-Hsu** [comment]
Thank you for the translations! I will look into an option where someone can easily switch between the languages in a future version. Thanks again!

**Comment by JohWiiner** [comment]
i've already make a menu to switch between the languages
