### ISSUE TITLE
WLAN TX Power tweak and number version

### ISSUE THREAD

**Issue by LoganMcClay** [Matthew-Hsu/PiPass#19]
Hi Matthew,

May I suggest two improvements to PiPass you may look into, first is managing the WiFi TX Power, by default it is set to 20 (20dBi), I myself turned it to 4 as it's enough range for me. I added to /etc/rc.local a line iwconfig wlan0 txpower 4 to achieve that at each reboot.
Second thing, would it be possible to add the version number to the web-gui, I haven't managed to see it anywhere, and I think it might be a plus to have it shown e.g. in top or footer bar.

Thanks for your work, and 1.4 works great for me :+1:

**Comment by Matthew-Hsu** [comment]
Hello Logan,

The versioning was long overdue and I have implemented a versioning widget on the main dashboard page. The widget is clickable, so you'll be able to view some brief notes about changes too.

As for the WiFi TX Power, I am probably going to avoid changes to /etc/rc.local and avoid changing WiFi TX Power values at this moment.

Thanks for the feedback and I am happy you are enjoying PiPass!
