### ISSUE TITLE
Can't connect to AP after MAC change

### ISSUE THREAD

**Issue by thamwangjun** [Matthew-Hsu/PiPass#2]
There are several times when after a MAC change, the AP from PiPass can't be accessed from the 3DS. 
I found out that the AP isn't there when I scanned for wifi networks through 3DS system settings. I checked and hostapd service is still running.
This only happens around once per 3 mac changes, and could be an isolated issue because of my wifi adapter. I'm running PiPass on a Raspberry Pi A+ under Raspbian.

I'm not sure if it is an elegant fix, but I added a line in piPass.py:

```
subprocess.Popen("sudo service hostapd restart", shell=True)
```

before this line:

```
time.sleep(STREETPASS_CYCLE_SECONDS)
```

**Comment by Matthew-Hsu** [comment]
Thanks for the feedback reyyed.

I haven't seen this particular issue with my setup, but I agree with your fix. Restarting hostapd on every MAC change would prevent the issue you are experiencing. I will patch this change and eliminate some other code that won't be needed anymore.

I'll test it out before I make another commit and possibly issue a hotfix on 1.1 in case anyone else was having the same issue.

Thanks again!
