### ISSUE TITLE
Add support for pitft

### ISSUE THREAD

**Issue by grimlokason** [Matthew-Hsu/PiPass#21]
Hello,

Do you think it'll be possible to add support for the PiTFT (at least from the framebuffer for the boot )?

More information are available here : https://www.adafruit.com/products/1601 and https://learn.adafruit.com/adafruit-pitft-28-inch-resistive-touchscreen-display-raspberry-pi
( I'll been available for testing it if you don't have one  )

Regards.

**Comment by Matthew-Hsu** [comment]
Hey Grimlokason,

Not sure if I will support it. I'm using a flavour of Raspbian that does not have a GUI pre-installed to keep installation size to a minimum.

With the source code available to download, you could always throw PiPass on a installation with support if you were thinking of using the touch screen to control PiPass.

Thanks.
