### ISSUE TITLE
PiPass App for Android and iOS

### ISSUE THREAD

**Issue by FamicomGuy** [Matthew-Hsu/PiPass#28]
You should make a PiPass App for Android and for iOS that lets you connect with the right IP address and have easy access to all configurations and the log file.

**Comment by Matthew-Hsu** [comment]
PiPass already has a mobile front end. If you use your Android or iPhone and enter the IP of your Pi into your mobile browser, you will see this layout. This is assuming that your device is on the same network.

A dedicated app would have the same limitations.
