### ISSUE TITLE
[Question] Does Pipass and Homepass still continue to work with latest 3ds update?

### ISSUE THREAD

**Issue by Corruptinglyneedful** [Matthew-Hsu/PiPass#41]
Damn 3DS is bugging me about a system update and I keep denying it because I'm unsure if Pipass will continue to work on it.  I've been waiting for confirmation here, but it hasn't popped up yet.

So I've been forced to directly ask.

**Comment by Matthew-Hsu** [comment]
If it's 9.8.0-25U, then yes, PiPass still works with it. I usually update right away and update the testing environment section in the readme to verify.
