### ISSUE TITLE
[Automatic Installer] Does not modify /etc/sudoers on Raspbian

### ISSUE THREAD

**Issue by tHubig** [Matthew-Hsu/PiPass#45]
I used the installer script to set up PiPass on a fresh install of Raspbian (on an old model B Raspberyy Pi) and it it appeared to succeed without error.  

Once I manually added my 3DS MAC address to /etc/hostapd/hostapd.conf, I got several streetpasses. 

HOWEVER, the nice web front end always says that PiPass is not running and appears not to work for anything, no matter how many times I refreshed it. There was nothing in the logs except a message that PiPass was not running.

It appears that 
www-data ALL=(ALL:ALL) NOPASSWD: ALL
was not added to /etc/sudoers.

Once I edited /etc/sudoers manually, things started working as expected.

**Comment by Matthew-Hsu** [comment]
What user and permissions did you run the script as? I am assuming it was a non-root user without enough privileges.

I've modified the line of the script where it writes www-data ALL=(ALL:ALL) NOPASSWD: ALL to /etc/sudoers. Normally, root can only write /etc/sudoers through visudo, but now I should elevate the permissions correctly to workaround this.

I've updated the installer script with that change.
