### ISSUE TITLE
Which hostapd driver to use for different USB dongles?

### ISSUE THREAD

**Issue by CCT-kun** [Matthew-Hsu/PiPass#47]
Hi, I'm using a TP-Link WN725N usb dongle. Which driver should I use in hostapd?

Thank you!

**Comment by Matthew-Hsu** [comment]
Hey,

It seems that WiFi adapter uses a RTL8188CUS chipset. There have been many problems with that chipset and others have not been able to get it working. With the way that Homepass works, the RTL8188CUS is problematic for any Raspberry Pi or Linux solution.

Realtek does provide a version of hostapd for that chipset, but it can become quite technical with no guarantee of working.

Others in your situation just opt to buy a compatible chipset, such as the ones listed on the project page. Generally they can range from $6 to $12.

Wish I had better news, but I hope this helps.
