### ISSUE TITLE
Edimax WiFi Adapter

### ISSUE THREAD

**Issue by Manaiakalani** [Matthew-Hsu/PiPass#50]
I purchased the Edimax EW-7811UN adapter from Amazon and am having a difficult time getting it set up. Can this be configured, or is it simply unsupported?

**Comment by Dagamant** [comment]
Someone figured out how to get that configured but I tried to follow the directions and a few vital pieces are missing like the modified hostapd driver.  Look for an adapter with the RT5370 chipset, they are about the same price as the edimax and don't need any special configuration.
