### ISSUE TITLE
Connecting to Nintendo servers?

### ISSUE THREAD

**Issue by naddel81** [Matthew-Hsu/PiPass#57]
Dear Matthew,

Thanksmfor your great project. I am interested in buying a Pi2 just for PiPass. I'd like to know to which servers streetpass connects to (or does it even use them? Because streetpass even works when you do not have an internet connection set up in your 3DS).

Background is: I use tubehax DNS to block Nintendo's eShop and update servers and would like to know if that interferes with PiPass.

Would be great to hear from you. Best wishes!

**Comment by sheepluva** [comment]
As far as I'm aware a -=New=- 3DS XL will connect to conntest.nintendowifi.net via HTTP (so TCP destination port 80) to check if its connected to the Internet.

If that check succeeds it will make new connections using HTTPS (so TCP destination port 443) to
api-us.olv.nintendo.net
conntest.nintendowifi.net
l-npns.app.nintendo.net
npdl.cdn.nintendowifi.net
nppl.c.app.nintendowifi.net
service.spr.app.nintendo.net

That's all I have observed so far.

I tested those addresses against the tubehax DNS server and it didn't seem like it was blocking any of them.
