### ISSUE TITLE
Disable Mac Filtering??

### ISSUE THREAD

**Issue by xabertheblade** [Matthew-Hsu/PiPass#61]
Bad practice, I know, but. . .Is there anyway to disable the MAC address filtering, or set it to a more permissive mode? I have quite a few friends that would like to partake in the street pass smorgasbord, however, I just don't want to deal with inputting so many DS MACS. I don't know how inadvisable this is, from a Nintendo-gets-pissy standpoint, but it would certainly simplify matters for me.

**Comment by kabili207** [comment]
In the settings menu, uncheck the `Hostapd Security` option.

> I don't know how inadvisable this is, from a Nintendo-gets-pissy standpoint, but it would certainly simplify matters for me.

Nintendo wouldn't care in the least bit. MAC filtering is used to prevent people from using your otherwise open access point for whatever they want.

**Comment by xabertheblade** [comment]
That seems much easier than I was expecting ;p Thank you very much for your reply :)
