### ISSUE TITLE
Getting StreetPasses while connected to home network?

### ISSUE THREAD

**Issue by kaizerfreak** [Matthew-Hsu/PiPass#63]
I suppose this isn't PiPass specific, just about the relays in general, but are you able to get StreetPasses if you're connected to your home network? I had to remove my home network from my connection settings (which was in the first spot) and then the StreetPasses started rolling in, but I'd like to keep my 3DS's primary connection as my home network.

**Comment by Loreinator** [comment]
If it is in sleep mode it _should_ work (closed).

**Comment by Dagamant** [comment]
Sorry to necro bump but I tested this and it does work as long as the DS is asleep. As soon as I close my lid and the MAC address advances I get more passes.
