### ISSUE TITLE
WPA2 authentication for attwifi?

### ISSUE THREAD

**Issue by RShadowhand** [Matthew-Hsu/PiPass#66]
Using RPi3 and latest version of PiPass. I want to add some sort of password to my attwifi because lots of people connect to it and use the internet.

I edited hostapd.conf to add some password, but my 3DS couldn't find it then, and starting PiPass re-writes the file every time.

**Comment by Loreinator** [comment]
Use the mac filter, they won't be able to connect if you have it limited by mac address to your 3DS only.

**Comment by RShadowhand** [comment]
Mac filter didn't work. I could still connect to it using my iPhone.

**Comment by davidmascenik** [comment]
DId you get PiPass working with the built-in wifi on RPi 3?

**Comment by RShadowhand** [comment]
Yeah. The image didn't work, it'd hang on black screen. So I downloaded the latest Raspbian version, and installed PiPass with the shell script (the installer one), and it just worked like that.
