### ISSUE TITLE
Raspberry 2 Model B, D-Link DWA-171 (RTL8811AU) driver issue

### ISSUE THREAD

**Issue by appeater** [Matthew-Hsu/PiPass#73]
Hi
First of, this seems like a nice piece of work. And it is an interesting project.
I just got my first Raspberry Pi 2, Mod B in order to run PiPass.
I seem to be having issues with my Wi-Fi dongle tho. I used the pre-made image, but PiPass is shutting down due to driver issues with my Realtek based D-Link dongle.

How would I go about solving this issue? I don't have any experience with Raspberry's, and my history with Linux goes as deep as to running OpenOffice back in elementary school.
Thank you for any input.

**Comment by Dagamant** [comment]
The RTL8811AU chipset is not directly supported and would require a modified hostapd driver.  Look for a dongle with the RT5370 chipset, they are cheap and do not require any extra effort to get working.
