### ISSUE TITLE
Firmware 11.1 breaks PiPass unless HOSTPAD security is disabled.

### ISSUE THREAD

**Issue by Maverynthia** [Matthew-Hsu/PiPass#76]
**EDIT: So, I accidentally seemed to have turned off Hostpad security trying to fix this and seems to "fix" the breakage.

Still a bit of an issue if people need it.**

So I stupidly updated my firmware just to download something and it seems that PiPass isn't working even using "attwifi" spots :c I even tried deleting my connections and only having PiPass running.

Is there a fix being worked on or is there no hope :c

**Comment by the4anoni** [comment]
How do you do that ?
Can,t do this on rpi 3 :(
