### ISSUE TITLE
Dashboard says "PiPass not started" even though its working

### ISSUE THREAD

**Issue by RoniRahman** [Matthew-Hsu/PiPass#77]
After I hit start in the settings, PiPass seems to start up just fine and I can see the ATT or McDonalds wifi or w.e. and my 3DS connects to it and everything works just fine. If I check under PiPass log files, it shows everything working fine as well. But the dashboard page says PiPass is not working or PiPass has not started or something to that affect (sorry, I'm not home right now so I dont have it in front of me). As someone else suggested, I tried Shift-Refreshing the page hoping its a cache issue and it kinda seems to be one? Sometimes after a shift-refresh, the page updates and the dashboard shows things working fine but other times shift-refreshing doesnt do anything to fix the dashboard so Im not convinced its just a UI caching issue. Not a major issue but when I first got into PiPass and didn't look at the log, I got really frustrated trying to figure out why things werent working without realizing things were working just fine in the background. This might be especially frustrating for the non tech-savvy or beginners. In any case, thanks for all the hard work, other than the dashboard, everything works like a charm.

**Comment by AdrienNguyenWorldline** [comment]
Same thing for me, streetpasses seems to work but dashboard shows nothing
