### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by suzsuzuki** [Matthew-Hsu/PiPass#95]
It seems Nintendo shut down their server. I get no more streetpasses. 

RIP HomePass

**Comment by ourovoros** [comment]
Do you know if there was an official announcement? Actually I was thinking the same thing. I've noticed that I have no streetpasses at all for several days ago, I reinstalled Linux and tried reinstalling PiPass, but it seems that I could not get streetpasses anymore. At first I thought that 3DS was broken, but the actual 3DS devices are communicating each other normally.

**Comment by ourovoros** [comment]
Ah, Please disregard previous comments. I found press release on Nintendo official site. According to it (https://www.nintendo.co.jp/support/information/2018/0228.html), they'd shutdown streetpass relay server on March/28/2018 10:00 AM JST. so I'd like to say thank you for PiPass.
